repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-added-large-files
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: detect-private-key
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
- repo: https://github.com/google/yapf
  rev: v0.32.0
  hooks:
    - id: yapf
      args: [ "-i", "-r" ]
      types: [ "python" ]
      additional_dependencies: [ "toml" ]
- repo: https://github.com/kynan/nbstripout
  rev: 0.6.0
  hooks:
    - id: nbstripout
      types: ["jupyter"]
      args: ["--drop-empty-cells",
             "--extra-keys 'metadata.language_info.version cell.metadata.jp-MarkdownHeadingCollapsed cell.metadata.pycharm'"]
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.225'
  hooks:
    - id: ruff
      # Respect `exclude` and `extend-exclude` settings.
      args: ["--force-exclude", "--fix"]
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.2
  hooks:
    - id: codespell
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
    - id: python-check-blanket-noqa
    - id: python-no-eval
    - id: python-no-log-warn
    - id: python-use-type-annotations
    - id: rst-backticks
    - id: rst-directive-colons
    - id: rst-inline-touching-normal
    - id: text-unicode-replacement-char
